#version: '3'
#services:
#  selenoid:
#    image: aerokube/selenoid:latest-release
#    container_name: selenoid
#    restart: always
#    network_mode: bridge
#    ports:
#      - "4444:4444"
#    volumes:
#    - "/path/to/config:/etc/selenoid"
#    - "/var/run/docker.sock:/var/run/docker.sock"
#    - "/path/to/config/video:/opt/selenoid/video"
#    - "/path/to/config/logs:/opt/selenoid/logs"
#    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir",
#               "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs",
#               "-container-network", "selenoid" ]
#
#  selenoid-ui:
#    image: aerokube/selenoid-ui:latest-release
#    network_mode: bridge
#    container_name: selenoid-ui
#    ports:
#      - "8080:8080"
#    links:
#      - selenoid
#    environment:
#      - SELENOID_URI=http://selenoid:4444

version: "3"
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "10"]
    ports:
      - 4444:4444
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"

  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest
    command: ["--webdriver-uri", "http://ggr:4444", "--status-uri", "http://ggr-ui:8888"]
    ports:
      - 8080:8080
    links:
      - selenoid
      - ggr-ui

  ggr:
    restart: always
    image: aerokube/ggr:latest
    ports:
      - 4444:4444
    volumes:
      -  "/etc/grid-router/:/etc/grid-router:ro"

  ggr-ui:
    network_mode: bridge
    restart: always
    image: aerokube/ggr-ui:latest
    ports:
      - 8888:8888
    volumes:
      -  "/etc/grid-router/quota:/etc/grid-router/quota:ro"

  chrome124:
    image: selenoid/vnc:chrome_124.0

  firefox124:
    image: selenoid/vnc:firefox_124.0