FROM jenkins/jenkins:lts

USER root

# Установка Maven
RUN apt-get update && apt-get install -y maven

# Установка Allure CLI
RUN apt-get install -y unzip curl \
    && curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip \
    && unzip allure.zip -d /opt/ \
    && mv /opt/allure-2.27.0 /opt/allure \
    && ln -s /opt/allure/bin/allure /usr/bin/allure

USER jenkins