version: "3"
services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "10"]
    ports:
      - "4444:4444"  # Основной порт Selenoid
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - selenoid-net

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"  # Порт UI
    environment:
      - SELENOID_URI=http://selenoid:4444
    depends_on:
      - selenoid
    networks:
      - selenoid-net

  chrome:
    image: selenoid/vnc:chrome_124.0
    networks:
      - selenoid-net
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo 'Browser container ready' && tail -f /dev/null"]

  firefox:
    image: selenoid/vnc:firefox_124.0
    networks:
      - selenoid-net
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo 'Browser container ready' && tail -f /dev/null"]

networks:
  selenoid-net:
    driver: bridge