version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-limit", "4",
      "-timeout", "3m",
      "-retry-count", "1"
    ]

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    restart: always
    ports:
      - "8080:8080"
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444