#version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    restart: always
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/dev/shm:/dev/shm"
    command: [
      "-limit", "4",
      "-timeout", "3m",
      "-retry-count", "1",
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video"
    ]
#    environment:
#      - DOCKER_API_VERSION=1.40

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    network_mode: bridge
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444