version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: always
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
    - "/path/to/config:/etc/selenoid"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/path/to/config/video:/opt/selenoid/video"
    - "/path/to/config/logs:/opt/selenoid/logs"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir",
               "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs",
               "-container-network", "selenoid" ]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444