#version: "3"
#services:
#  selenoid:
#    container_name: selenoid
#    image: aerokube/selenoid:latest
#    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "10"]
#    ports:
#      - "4444:4444"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./config:/etc/selenoid"
#    networks:
#      - selenoid-net
#
#  selenoid-ui:
#    image: aerokube/selenoid-ui:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - SELENOID_URI=http://selenoid:4444
#    depends_on:
#      - selenoid
#    networks:
#      - selenoid-net
#
#networks:
#  selenoid-net:
#    driver: bridge