##version: '3'
#services:
#  selenoid:
#    image: aerokube/selenoid:latest-release
#    container_name: selenoid
#    restart: always
#    network_mode: bridge
#    ports:
#      - "4444:4444"
#    volumes:
#      - "./config:/etc/selenoid"
#      - "/var/run/docker.sock:/var/run/docker.sock:rw"
#      - "/dev/shm:/dev/shm"
#    command: [
#      "-limit", "4",
#      "-timeout", "3m",
#      "-retry-count", "1",
#      "-conf", "/etc/selenoid/browsers.json",
#      "-video-output-dir", "/opt/selenoid/video"
#    ]
##    environment:
##      - DOCKER_API_VERSION=1.40

version: '3'
networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created
services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "/path/to/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/path/to/config/video:/opt/selenoid/video"
      - "/path/to/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444